# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-23 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, db_tablespace='indexes')),
                ('created', models.DateTimeField(auto_now_add=True, db_tablespace='indexes')),
                ('sentiment', models.IntegerField(choices=[(1, 'Positif'), (-1, 'Negatif'), (0, 'Neutre'), (2, 'Inconnu')], default=2)),
                ('topic', models.IntegerField(choices=[(0, 'General'), (1, 'Economie'), (2, 'Parti socialiste'), (3, 'Les republicains'), (4, 'Front National')], default=0)),
                ('txt', models.CharField(max_length=200)),
                ('usr_twitter_id', models.IntegerField()),
                ('replied_to', models.IntegerField(verbose_name=-1)),
                ('lang', models.CharField(default='FR', max_length=10)),
                ('place', models.CharField(default='NULL', max_length=30)),
            ],
        ),
    ]
