# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0002_auto_20170124_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='sentiment',
            new_name='sentiment_predicted',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='topic',
        ),
        migrations.AddField(
            model_name='tweet',
            name='sentiment_label',
            field=models.IntegerField(choices=[(1, 'Positif'), (-1, 'Negatif'), (0, 'Neutre'), (2, 'Inconnu')], db_tablespace='indexes', default=2, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='topic_label',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'General'), (1, 'Economie'), (2, 'Sante'), (3, 'Parti Socialiste'), (4, 'Les Republicains'), (5, 'Front National'), (6, 'En Marche')], max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='topic_predicted',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'General'), (1, 'Economie'), (2, 'Sante'), (3, 'Parti Socialiste'), (4, 'Les Republicains'), (5, 'Front National'), (6, 'En Marche')], default=0, max_length=13),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='lang',
            field=models.CharField(db_tablespace='indexes', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='place',
            field=models.CharField(db_tablespace='indexes', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='replied_to',
            field=models.IntegerField(db_tablespace='indexes', null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='usr_twitter_id',
            field=models.IntegerField(db_tablespace='indexes', null=True),
        ),
    ]
