# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0003_auto_20170124_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='sentiment_label',
            field=models.IntegerField(choices=[(1, 'Positif'), (-1, 'Negatif'), (0, 'Neutre'), (2, 'Inconnu')], db_tablespace='indexes', null=True),
        ),
    ]
