# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-26 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0005_auto_20170124_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='coordinates',
            field=models.CharField(db_tablespace='indexes', max_length=30, null=True),
        ),
    ]
