# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-30 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0006_tweet_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='txt',
            field=models.TextField(db_tablespace='indexes'),
        ),
    ]
