# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-31 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0008_tweet_usr_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='coordinates',
            field=models.CharField(db_tablespace='indexes', max_length=200, null=True),
        ),
    ]
