# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-31 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0009_auto_20170131_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='sentiment_label',
            field=models.IntegerField(choices=[(0, 'Neutre'), (2, 'Inconnu'), (1, 'Positif'), (-1, 'Negatif')], db_tablespace='indexes', null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='sentiment_predicted',
            field=models.IntegerField(choices=[(0, 'Neutre'), (2, 'Inconnu'), (1, 'Positif'), (-1, 'Negatif')], db_tablespace='indexes', null=True),
        ),
    ]
