# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-31 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0010_auto_20170131_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='retweet',
            field=models.TextField(db_tablespace='indexes', null=True),
        ),
    ]
