# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0012_auto_20170131_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='topic_label',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='topic_predicted',
        ),
    ]
