# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-02 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0013_auto_20170201_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='coordinates',
            field=models.TextField(db_tablespace='indexes', null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='place',
            field=models.CharField(db_tablespace='indexes', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='usr_place',
            field=models.CharField(db_tablespace='indexes', max_length=50, null=True),
        ),
    ]
