# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0015_auto_20170206_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='place',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='replied_to',
        ),
        migrations.AddField(
            model_name='tweet',
            name='added_carte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tweet',
            name='added_carte_pred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tweet',
            name='usr_region',
            field=models.CharField(db_tablespace='indexes', max_length=60, null=True),
        ),
    ]
