# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-20 18:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listener', '0017_auto_20170213_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_code', models.CharField(default='', max_length=20)),
                ('num_tests', models.IntegerField(blank=True, default=0)),
                ('num_tweets_labelled', models.IntegerField(blank=True, default=0)),
                ('staff', models.IntegerField(blank=True, choices=[(1, 'L2L'), (0, 'Normal User')], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
