# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-20 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0019_auto_20170220_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='in_reply_to',
            field=models.CharField(db_tablespace='indexes', max_length=30, null=True),
        ),
    ]
