# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-09 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0021_tweet_usr_screen_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='sentiment_alchemy',
            field=models.IntegerField(choices=[(1, 'Positif'), (-1, 'Negatif'), (0, 'Neutre'), (2, 'Inconnu')], db_tablespace='indexes', null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='usr_place',
            field=models.CharField(db_tablespace='indexes', max_length=80, null=True),
        ),
    ]
