# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-14 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=60)),
                ('name2', models.CharField(max_length=60)),
                ('geometry_coord', models.TextField(null=True)),
                ('geometry_type', models.CharField(default='MultiPolygon', max_length=20)),
                ('num_tweets_pos', models.IntegerField(default=0)),
                ('num_tweets_neg', models.IntegerField(default=0)),
                ('num_tweets_net', models.IntegerField(default=0)),
                ('num_tweets_pos_pred', models.IntegerField(default=0)),
                ('num_tweets_neg_pred', models.IntegerField(default=0)),
                ('num_tweets_net_pred', models.IntegerField(default=0)),
                ('color', models.CharField(default='GREY', max_length=20)),
                ('color_pred', models.CharField(default='GREY', max_length=20)),
            ],
        ),
    ]
