# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-10 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartementFRModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.IntegerField()),
                ('region_code', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
                ('name_complete', models.CharField(max_length=60)),
                ('geometry', models.TextField(null=True)),
                ('num_tweets_pos', models.IntegerField(null=True)),
                ('num_tweets_neg', models.IntegerField(null=True)),
                ('num_tweets_net', models.IntegerField(null=True)),
                ('color', models.CharField(default='GREY', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RegionFRModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
                ('name2', models.CharField(max_length=60)),
                ('geometry', models.TextField(null=True)),
                ('num_tweets_pos', models.IntegerField(null=True)),
                ('num_tweets_neg', models.IntegerField(null=True)),
                ('num_tweets_net', models.IntegerField(null=True)),
                ('color', models.CharField(default='GREY', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VilleFRModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.IntegerField()),
                ('region_code', models.IntegerField()),
                ('department_code', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
                ('name_complete', models.CharField(max_length=60)),
                ('geometry', models.TextField(null=True)),
                ('num_tweets_pos', models.IntegerField(null=True)),
                ('num_tweets_neg', models.IntegerField(null=True)),
                ('num_tweets_net', models.IntegerField(null=True)),
                ('color', models.CharField(default='GREY', max_length=10)),
            ],
        ),
    ]
