# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-10 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_departementfrmodel_regionfrmodel_villefrmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionfrmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='departementfrmodel',
            name='region_code',
        ),
        migrations.AlterField(
            model_name='regionfrmodel',
            name='code',
        ),
        migrations.AlterField(
            model_name='villefrmodel',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='villefrmodel',
            name='department_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='villefrmodel',
            name='region_code',
        ),
    ]
