# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-11 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20170210_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departementfrmodel',
            name='region_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='villefrmodel',
            name='region_code',
            field=models.IntegerField(),
        ),
    ]
