# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-11 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20170211_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departementfrmodel',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
