# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-11 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20170211_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departementfrmodel',
            name='name_complete',
        ),
        migrations.AlterField(
            model_name='villefrmodel',
            name='name_complete',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
