# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-11 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20170211_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villefrmodel',
            name='code',
        ),

    ]
