# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-11 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_auto_20170211_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villefrmodel',
            name='name_complete',
        ),
    ]
