# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-11 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_remove_villefrmodel_name_complete'),
    ]

    operations = [

        migrations.AlterField(
            model_name='villefrmodel',
            name='name',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
