# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-11 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_auto_20170211_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='villefrmodel',
            name='id',
            field=models.AutoField(auto_created=True, default=-1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='villefrmodel',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
