# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-11 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_auto_20170211_0105'),
    ]

    operations = [

        migrations.AlterField(
            model_name='villefrmodel',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
