# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-11 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_auto_20170211_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionfrmodel',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
