# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-12 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_auto_20170211_1237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Departement',
        ),
        migrations.AlterField(
            model_name='region',
            name='num_tweets_neg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='num_tweets_net',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='num_tweets_pos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
