# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0015_auto_20170213_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='geometry',
            new_name='geometry_coord',
        ),
        migrations.AddField(
            model_name='region',
            name='geometry_type',
            field=models.CharField(default='MultiPolygon', max_length=20),
        ),
    ]
